### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TimHobbes** [RandyCupic/RuneAudioLCD#4]
When I start start.py with the commando python2 start.py is get the error:
Traceback (most recent call last):
  File "start.py", line 117, in <module>
    display = i2c_display.i2c_display(I2C_DISPLAY_ADDRESS, LCD_ROWS, LCD_COLUMNS, TEMPORARY_SCREEN_PERIOD, SCROLLING_PERIOD)
  File "/root/RuneAudioLCD-master/display.py", line 20, in __init__
    self.lcd_initialize()
  File "/root/RuneAudioLCD-master/i2c_display.py", line 102, in lcd_initialize
    self.lcd_device = i2c_device(self.address)
  File "/root/RuneAudioLCD-master/i2c_display.py", line 79, in __init__
    self.bus = smbus.SMBus(port)
IOError: [Errno 2] No such file or directory

**Comment by RandyCupic** [comment]
Hello,

Take a look on the installation tutorial: http://www.runeaudio.com/forum/lcd-display-and-buttons-in-python-tutorial-and-code-t1191.html

Search for "smbus" and there you will find what you should do to remove this problem with smbus.

This is only a workaround. I have to retype this script to make it better and easier to install.
